package com.mark.codingtest.leetcode.editor.en;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;

import java.util.HashMap;
import java.util.Map;

//You are given two strings s and t. 
//
// String t is generated by random shuffling string s and then add one more 
//letter at a random position. 
//
// Return the letter that was added to t. 
//
// 
// Example 1: 
//
// 
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
// 
//
// Example 2: 
//
// 
//Input: s = "", t = "y"
//Output: "y"
// 
//
// 
// Constraints: 
//
// 
// 0 <= s.length <= 1000 
// t.length == s.length + 1 
// s and t consist of lowercase English letters. 
// 
//
// Related Topics Hash Table String Bit Manipulation Sorting 👍 5011 👎 482


@Slf4j
public class FindTheDifference_389 {

    @Test
    void test() {
        log.info("result: {}", new Solution().findTheDifferenceUsingBit("abcd", "abcde"));
//        log.info("result: {}", new Solution().findTheDifference("", "y"));
    }

    //leetcode submit region begin(Prohibit modification and deletion)
    class Solution {

        /**
         * <b>HashTable</b>
         */
        public char findTheDifference(String s, String t) {
            Map<Character, Integer> map = new HashMap<>();
            for (char c : s.toCharArray()) {
                map.put(c, map.getOrDefault(c, 0) + 1);
            }

            for (char c : t.toCharArray()) {
                map.put(c, map.getOrDefault(c, 0) - 1);
                if (map.get(c) < 0) {
                    return c;
                }
            }

            return t.charAt(0);
        }

        /**
         * <b>Bit</b>
         */
        public char findTheDifferenceUsingBit(String s, String t) {
            char result = 0;
            for (char c : s.toCharArray()) {
                result ^= c;
            }
            for (char c : t.toCharArray()) {
                result ^= c;
            }
            return result;
        }
    }
    //leetcode submit region end(Prohibit modification and deletion)

}